### ISSUE TITLE
Messaging widl is incorrect

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/actor-interfaces#18]
The messaging widl sitting in the schemas directory right now doesn't include the `DeliverMessage` operation, which is used by the messaging capability provider to deliver messages to an actor.

This is required so that PR #17 can be updated so that the relevant actor code can work properly.

**Comment by autodidaddict** [comment]
Apologies I didn't take care of this yet... was working on some other stuff after vacation ended.

**Comment by alanpoon** [comment]
<img width="496" alt="Screenshot 2021-01-24 at 7 32 15 AM" src="https://user-images.githubusercontent.com/8205468/105617028-99597400-5e16-11eb-811e-5963baa1fe11.png">
widl parsing error at messaging.widl
