### ISSUE TITLE
Add first-class function for actor-to-actor call (Rust)

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/actor-interfaces#26]
In the `actor-core` crate, add a function that gives the actor developer the ability to make direct actor-to-actor function calls. While this is possible now using primitive `wapc_guest` functionality, it's certainly not intuitive. Our documentation should reflect that support for actor-to-actor comms is a fully supported thing.

A possible name for the function would be a module-level public function called `call_actor(actor_ref: &str, op: &str, payload: &[u8]) -> InvocationResponse` , this returns a standard opaque response applying no meaning to the internal payload. Applying meaning or structure to the response would be up to the actor.

Once this feature is implemented, one of the examples in the public examples repository needs to illustrate how (and why) you would do actor-to-actor calls.

**Comment by autodidaddict** [comment]
Thinking about this some more, I don't think we should even have the payload be a raw set of bytes. If the actor developer knows ahead of time that they're using the wasmCloud default serialization mechanism (messagepack), then we should just be able to pass anything that implements `Serialize` and we can do the work on their behalf, so an actor-to-actor call might look like this:

```rust
let res = core::call_actor("my.registry.io/hello:v2", "CalculateStuff", CalculatorInput::new(5, 4, 2));
```

This also implies that actors can be invoked either by their OCI reference or by public key. Obviously an invocation response failure will be returned if the lattice cannot locate an actor by the given OCI reference.

**Comment by autodidaddict** [comment]
We'll also need some way to make it easy for actors to register a custom handler for a named operation, e.g. something that they can put in the `wapc_init` function:

```rust
#[no_mangle]
pub fn wapc_init() {
    actorcore::Handlers::register_health_request(health);
    actorcore::Handlers::register_custom_handler("CalculateStuff", calculate_handler);
}
```

And this might register a handler using some combination of generics and cleverness to not make this signature any more complex than it has to be. Ultimately it's just going to be a wrapper around the `wapc-guest` function `register_function`

**Comment by brooksmtownsend** [comment]
This has been completed with #53
