### ISSUE TITLE
Create telnet interface (Rust)

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/actor-interfaces#3]
Create a wrapper crate around the telnet interface

**Comment by brooksmtownsend** [comment]
With https://github.com/wasmCloud/actor-interfaces/tree/main/rust/telnet, can we close this @autodidaddict ?

**Comment by autodidaddict** [comment]
Looks like it. Forgot there was an open issue for this.

**Comment by brooksmtownsend** [comment]
Closed by #21
