### ISSUE TITLE
Introduce versions to our interfaces

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/actor-interfaces#79]
A fair point is brought up in https://github.com/wasmCloud/wasmCloud/issues/175 that we don't currently version our `widl` interfaces at all. We do have semver enforced in the different language interfaces, but the actual interface is still versionless. I propose we start all of our interfaces at `v0.1.0` and update their namespace as per the documentation suggests:https://github.com/wapc/widl-spec/blob/main/README.md#namespace.

For example, our current Extras contract namespace is `wasmcloud:extras`. This would change the namespace to `wasmcloud:extras.v0.1.0`. This should not affect our capability contract IDs however, so if there is any affect to the contract ID this can be reconsidered.

**Comment by VestigeJ** [comment]
Should versions of the interfaces be tied to wasmcloud version numbers?

**Comment by autodidaddict** [comment]
> Should versions of the interfaces be tied to wasmcloud version numbers?

No.

**Comment by autodidaddict** [comment]
I am okay with the idea of putting a version in the contract identifier, but typically interface / schema versioning is done like `v1` and then `v2` etc. This is a typical pattern with REST contracts, gRPC contracts, etc.

So if we're going to version the _contract_ (which is different than the rust crate), I suggest we follow that pattern, e.g.

`wasmcloud:extras.v1` , `wasmcloud:httpserver.v1` etc

**Comment by brooksmtownsend** [comment]
Agreed, I think everything is going to stay independently versioned, the interface may stay the same over multiple versions of wasmcloud or the actual generated interface as well (if we have to make a change to a single language interface for example). Re: @autodidaddict 's suggestion for `v1` / `v2`, I am good with that too. All in all our contracts shouldn't be changing often anyways

**Comment by autodidaddict** [comment]
> This should not affect our capability contract IDs however

The capability contract ID is actually pulled straight from the namespace in the widl file. So changing it in the widl file and regenerating will break APIs on both sides of the contract.

Further, it will change the way link definitions are specified, e.g. all previous link definitions using `wasmcloud:httpserver` would have to be changed to `wasmcloud:httpserver.v1`

**Comment by autodidaddict** [comment]
Another thing to consider is whether we should make changes to our namespaces, or whether widl should get an enhancement to support schema versioning as a first-class piece of metadata. cc/ @pkedy

**Comment by brooksmtownsend** [comment]
It does appear that it would directly put the version into the contract ID:
```
➜ diff src/generated.rs src/generated-old.rs
43c43
<         host_call(&self.binding, "wasmcloud:extras.v1", "RequestGuid", &vec![])
---
>         host_call(&self.binding, "wasmcloud:extras", "RequestGuid", &vec![])
56c56
<             "wasmcloud:extras.v1",
---
>             "wasmcloud:extras",
70c70
<             "wasmcloud:extras.v1",
---
>             "wasmcloud:extras",
```

So, the codegen library should (for our use case) remove the version prefix from the host/guest operation. I can get tunnel-visioned with widl/wapc/wasmcloud, so looking to @pkedy if this affects non-wasmcloud use cases. In any case, if the codegen library doesn't change to remove the version tag, it would feel hacky to remove it from the namespace and it may be better as a widl schema version

**Comment by stevelr** [comment]
Versioning can happen at several places:

- All smithy services have a version number in them, so we have a baseline that the code generator can use going forward. If needed, we could add version info to the metadata in smithy files.

- Capability contract ids can be versioned by adding a ":v2" suffix _if_ there is a breaking change.

- Additionally (via separate issues) we are adding a version number for wasmbus rpc protocol version, so actrors and capability providers can report to the host which version of protocol they support. That could accommodate future changes to wapc such as serialization.
