### ISSUE TITLE
Revert extras interface to GeneratorResult result

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/actor-interfaces#83]
With the mass re-architecting of the interfaces in #40 , the extras interface was changed in a way that would warrant a minor release, rather than a patch release. This breaks the contract for version `0.1.2`, and should be reverted back to the single result type of `GeneratorResult`. If this return type isn't the desired contract for `wasmcloud:extras`, it should be changed in the future for version `0.2.0`.

**Comment by stevelr** [comment]
fix in issue #114

**Comment by brooksmtownsend** [comment]
Just noting that this is also reflected in https://github.com/wasmCloud/wasmCloud/issues/175.

**Comment by stevelr** [comment]
The extras interface has been replaced by interfaces/numbergen, so at least this is moot for the 0.50 release.

If we don't plan to change the existing extras interface for 0.18/0.19, please close this.

**Comment by brooksmtownsend** [comment]
This interface should be reverted for compatibility, as it's currently not functional.

**Comment by brooksmtownsend** [comment]
This is in a PR https://github.com/wasmCloud/actor-interfaces/pull/86, looking for a review @autodidaddict
